#!/bin/sh

set -e

arch="$(uname -m)"

curl -O -L "https://github.com/facebook/dotslash/releases/download/v0.5.5/dotslash-linux-musl.${arch}.tar.gz"

sha256sum --check --ignore-missing <<'SUMS'
e60de8814a1fe6dcbb07d1263e7a512f328f8a39a69a35b32416240164a40232  dotslash-linux-musl.aarch64.tar.gz
221ef28550ec6164a507560ca86e50be59d8160c39f7f93dfd2479e680a061ca  dotslash-linux-musl.x86_64.tar.gz
SUMS

tar -xzf dotslash-linux-musl.${arch}.tar.gz
