#!/bin/sh

set -e

if [ "$(uname -m)" = "aarch64" ]; then
    curl -o dotslash.tgz -L https://github.com/facebook/dotslash/releases/download/v0.5.0/dotslash-linux-musl.arm64.v0.5.0.tar.gz
    echo "12882526a7c00fa721518a7da4058d0579954cbfbe7280d8c10759316f419959  dotslash.tgz" | sha256sum --check
else
    curl -o dotslash.tgz -L https://github.com/facebook/dotslash/releases/download/v0.5.0/dotslash-linux-musl.x86_64.v0.5.0.tar.gz
    echo "373688a5597d05bf215d5db8a736babf6358a50f09cefa6bedb405a8960f88db  dotslash.tgz" | sha256sum --check
fi

tar -xvzf dotslash.tgz
