name: docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout dotslash
        uses: actions/checkout@v4
        with:
          repository: facebook/dotslash
          ref: v0.4.1
          path: dotslash
      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
        with:
          image: tonistiigi/binfmt:master@sha256:3d5cb3f4254851fb1ebc7e9758d888af955079c06ead3745fce0f0841e2ec591
          platforms: arm64,amd64
      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0
      - name: docker-login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index # https://github.com/docker/build-push-action/issues/900
        with:
          images: ghcr.io/${{ github.actor }}/dotslash
          tags: |
            type=raw,value=bookworm
          labels: |
            org.opencontainers.image.description=dotslash
            org.opencontainers.image.title=dotslash
          annotations: |
            org.opencontainers.image.description=dotslash
            org.opencontainers.image.title=dotslash
      - name: build-and-push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: false # https://github.com/docker/build-push-action/issues/900
